Lab2_KM/Controllers/FarmacosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab2_KM.Utils;
using Lab2_KM.Models;

namespace Lab2_KM.Controllers
{
    public class FarmacosController : Controller
    {
        // GET: FarmacosController
        public ActionResult Index(int page = 1)
        {
            if (Storage.Instance.ArbolAVL.listaInOrder.Count > 0)
            {
                Storage.Instance.ArbolAVL.listaInOrder.Clear();
            }
            
            Storage.Instance.ArbolAVL.InOrder(Storage.Instance.ArbolAVL.padre);
            var paginacionFarmacos = new paginacion
            {
                farmacosPorPagina = 50,
                farmacos = Storage.Instance.ArbolAVL.listaInOrder,
                paginaActual = page
            };

            Storage.Instance.pagination = paginacionFarmacos;
            return View("Index", Storage.Instance.pagination);
        }

        [HttpGet]
        public ActionResult DataFarmaco(string ID, string NOMBRE)
        {
            LstDoblementeEnlazada.Nodo<InventarioFarmacos> nodoFarmaco = new LstDoblementeEnlazada.Nodo<InventarioFarmacos>();

            nodoFarmaco = Storage.Instance.listaArtesanal.buscar(Storage.Instance.listaArtesanal.nodoRaiz, ID, Storage.Instance.listaArtesanal.nodoRaiz.elemento.compararFarmaco);
            

            if (nodoFarmaco.elemento.existencia > 0)
            {
                nodoFarmaco.elemento.existencia--;
                Storage.Instance.listaFarmacos.Add(nodoFarmaco.elemento);
                return View("Index", Storage.Instance.pagination);

            }
            else {
                
                return View("Index", Storage.Instance.pagination);

            }
            
            
        }

        public ActionResult buscarFarmaco() {
            return View();
        }

        [HttpPost]
        public ActionResult buscarFarmaco(IFormCollection collection)
        {
            string busqueda = collection["Busqueda"];


            LibFarmacos.Nodo<FarmacoArbol> nodoFarmacoEncontrado = Storage.Instance.ArbolAVL.Buscar(Storage.Instance.ArbolAVL.padre,
                busqueda, Storage.Instance.ArbolAVL.padre.valorFarmaco.buscarFarmacoBinario);

            LstDoblementeEnlazada.Nodo<InventarioFarmacos> Busqueda = Storage.Instance.listaArtesanal.buscar(Storage.Instance.listaArtesanal.nodoRaiz,
                nodoFarmacoEncontrado.valorFarmaco.id, Storage.Instance.listaArtesanal.nodoRaiz.elemento.compararFarmaco);

            
            return View("ResultadoBusqueda", Busqueda.elemento);
        }


        [HttpGet]
        public ActionResult abastecerFarmaco(string nombreFarmaco)
        {
            LibFarmacos.Nodo<FarmacoArbol> nodoFarmacoEncontrado = Storage.Instance.ArbolAVL.Buscar(Storage.Instance.ArbolAVL.padre,
               nombreFarmaco, Storage.Instance.ArbolAVL.padre.valorFarmaco.buscarFarmacoBinario);
            

            LstDoblementeEnlazada.Nodo<InventarioFarmacos> Busqueda = Storage.Instance.listaArtesanal.buscar(Storage.Instance.listaArtesanal.nodoRaiz,
                nodoFarmacoEncontrado.valorFarmaco.id, Storage.Instance.listaArtesanal.nodoRaiz.elemento.compararFarmaco);

            return View("abastecer", Busqueda.elemento);
        }


        [HttpPost]
        public ActionResult abastecerFarmaco(string NOMBRE, IFormCollection collection)
        {
            
            int existencia = int.Parse(collection["Existencia"]);


            LibFarmacos.Nodo<FarmacoArbol> nodoFarmacoEncontradoAux = Storage.Instance.ArbolAVL.Buscar(Storage.Instance.ArbolAVL.padre,
               NOMBRE, Storage.Instance.ArbolAVL.padre.valorFarmaco.buscarFarmacoBinario);

            LibFarmacos.Nodo<FarmacoArbol> nodoFarmacoEncontrado = Storage.Instance.ArbolAVL.Buscar(Storage.Instance.ArbolAVL.padre,
               NOMBRE, Storage.Instance.ArbolAVL.padre.valorFarmaco.buscarFarmacoBinario);

            LstDoblementeEnlazada.Nodo<InventarioFarmacos> Busqueda = Storage.Instance.listaArtesanal.buscar(Storage.Instance.listaArtesanal.nodoRaiz,
                nodoFarmacoEncontrado.valorFarmaco.id, Storage.Instance.listaArtesanal.nodoRaiz.elemento.compararFarmaco);

            Busqueda.elemento.existencia = existencia;

            FarmacoArbol nodoAuxiliar = new FarmacoArbol();



            nodoAuxiliar.id = nodoFarmacoEncontrado.valorFarmaco.id;
            nodoAuxiliar.NombreFarmaco = nodoFarmacoEncontrado.valorFarmaco.NombreFarmaco;

           

            // Eliminacion del farmaco del arbol B
            Storage.Instance.ArbolAVL.Eliminar(Busqueda.elemento.NombreFarmaco, 
                Storage.Instance.ArbolAVL.padre.valorFarmaco.buscarEliminacionFarmacoBinario);


           

            Storage.Instance.ArbolAVL.insertar(nodoAuxiliar,
              Storage.Instance.ArbolAVL.padre.valorFarmaco.CompararNombreF);

            

        
            return View("Index", Storage.Instance.pagination);
        }


    }
}

Lab2_KM/Views/Farmacos/Index.cshtml
@using Lab2_KM.Utils;
@using Lab2_KM.Models;
@model Lab2_KM.Models.paginacion




@foreach (var farmaco in Model.pags())
{
    <div class="card horizontal">
        <div class="card-stacked">
            <div class="card-content">
                <p>@farmaco.NombreFarmaco</p>
            </div>
            <div class="card-action">
                <a class="waves-effect waves-light btn" href="/Farmacos/DataFarmaco?ID=@farmaco.id&NOMBRE=@farmaco.NombreFarmaco"><i class="material-icons left">cloud</i>Agregar A Pedido</a>


            </div>
        </div>
    </div>
}

<ul class="pagination">
    <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
    
    @for (int i = 1; i <= Model.paginas(); i++)
    {
        <li class="waves-effect @(i== Model.paginaActual ? "active": "")">
            <a href="@Url.Action("Index", new { page = i})">@i</a>
        </li>
    }
    <li class="waves-effect"><a><i class="material-icons">chevron_right</i></a></li>
</ul>

Lab2_KM/Views/Farmacos/ResultadoBusqueda.cshtml
@model Lab2_KM.Models.InventarioFarmacos


<div class="card horizontal">
    <div class="card-stacked">
        <div class="card-content">
            <p>@Model.NombreFarmaco</p>
        </div>
        <div class="card-action flex-column">
            <p>Descripcion: @Model.descripcion</p>
            <p>Casa Productora: @Model.CasaProductora</p>
            <p>Existencia: @Model.existencia</p>
            <p>Precio: @Model.precio</p>

            @{
                if (Model.existencia == 0)
                {
                    <a class="waves-effect waves-light btn red" href="/Farmacos/abastecerFarmaco?nombreFarmaco=@Model.NombreFarmaco"><i class="material-icons left">cloud</i>Abastecer</a>
                }
                else
                {
                    <a class="waves-effect waves-light btn" href="/Farmacos/DataFarmaco?ID=@Model.Id&NOMBRE=@Model.NombreFarmaco"><i class="material-icons left">cloud</i>Agregar A Pedido</a>
                }
            }

        </div>
    </div>
</div>

Lab2_KM/Views/Farmacos/abastecer.cshtml
@using Lab2_KM.Models
@model InventarioFarmacos

<div class="row">
    <form class="col s12" method="post" action="/Farmacos/abastecerFarmaco?NOMBRE=@Model.NombreFarmaco">

        <h2 class="center red-text">@Model.NombreFarmaco</h2>

        <div class="row">
            <p class="range-field">
                <label> Existencia </label>
                <input type="range" name="Existencia" min="0" max="15" />
            </p>
        </div>

            <button class="btn waves-effect waves-light" type="submit">
                Submit
                <i class="material-icons right">send</i>
            </button>

    </form>
</div>

Lab2_KM/Views/Farmacos/buscarFarmaco.cshtml
<div class="row">
    <form class="col s12 center" method="post" action="@Url.Action("buscarFarmaco", "Farmacos")">

        <div class="row">
            <div class="input-field col s12">
                <input id="search" type="text" class="validate" name="Busqueda">
                <label for="search">Buscar</label>
            </div>
        </div>

        <button class="btn waves-effect waves-light center" type="submit" >
            Buscar
            <i class="material-icons right">search</i>
        </button>


    </form>
</div>