Lab2_KM/Controllers/CargaDatosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab2_KM.Utils;
using System.IO;
using System.Threading.Tasks;
using LibFarmacos;
using Lab2_KM.Models;
using Microsoft.AspNetCore.Hosting;

namespace Lab2_KM.Controllers
{
    public class CargaDatosController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public CargaDatosController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> cargaArchivo(IFormFile file)
        {
            //Folde o Carpeta
            string csvFolder = Path.Combine(_hostingEnvironment.WebRootPath, "csv");
            // Nombre Archivo
            var fileName = string.Empty;

            var path = string.Empty;

            string filePath = "";


            if (file.Length > 0)
            {
                //wwwroot/csv/MoclUdata(4).csv
                filePath = Path.Combine(csvFolder, file.FileName);
                
                //MockData(4)
                fileName = Path.GetFileName(file.FileName);

                using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    //Copia el archivo del servidor a la direccion fisica
                    await file.CopyToAsync(fileStream);
                }
            }

            Reader reader = new Reader(filePath);
            //Storage.Instance.ArbolB.ToString();
            Storage.Instance.ArbolAVL.ToString();
            Storage.Instance.listaArtesanal.ToString();

            return RedirectToAction("Index", "Farmacos");
        }

        
    }
}

Lab2_KM/Views/CargaDatos/Index.cshtml
@using Lab2_KM.Utils;
@{ ViewData["Title"] = "Data Loader"; }

<h1 class="header center orange-text">Carga de Datos</h1>
<div class="row center">
    <h5 class="header col s12 light">Seleccionar archivo</h5>

</div>

<form enctype="multipart/form-data" action="@Url.Action("cargaArchivo", "CargaDatos")" class="col s12" method="post">
    <div class="row">
        <label>Selector de Archivo</label>
        <div class="file-field input-field">
            <div class="btn">
                <span>Seleccionar</span>
                <input type="file" name="file" />
            </div>

            <div class="file-path-wrapper">
                <input class="file-path validate" type="text"
                       placeholder="Archivo subido" />
            </div>
        </div>
    </div>
    <button class="btn waves-effect waves-light center" type="submit">
        Submit
        <i class="material-icons right">send</i>
    </button>
</form>

Lab2_KM/Views/CargaDatos/cargaArchivo.cshtml
@using Lab2_KM.Utils;
@{
    ViewData["Title"] = "File loader";
}

<h1 class="header center orange-text">Carga de Datos</h1>
<div class="row center">
    <h5 class="header col s12 light">Carga inventario de medicamentos</h5>
</div>


<form enctype="multipart/form-data" action="@Url.Action("cargaArchivo", "CargaDatos")" class="col s12" method="post">
    <div class="row">
        <label>Selector de Archivo</label>
        <div class="file-field input-field">
            <div class="btn">
                <span>Seleccionar</span>
                <input type="file" name="file" />
            </div>

            <div class="file-path-wrapper">
                <input class="file-path validate" type="text"
                       placeholder="Archivo subido" />
            </div>
        </div>
    </div>
    <button class="btn waves-effect waves-light center" type="submit" name="action">
        Submit
        <i class="material-icons right">send</i>
    </button>
</form>

Lab2_KM/Views/CargaDatos/listaArtesanal.cshtml
@using Lab2_KM.Utils;
@*@using LstDoblementeEnlazada;
@model ListaDobleEnl<string>;*@

@{ ViewData["Title"] = "Medicamentos"; }

<h1 class="header center orange-text">Índice</h1>
<div class="row center">
    <h5 class="header col s12 light">Índice de Fármacos</h5>

</div>

<div class="row">
    @*{ 
    @if (Model.nodoRaiz != null)
    {
        Nodo<string> nodoActual = new Nodo<string>();
        nodoActual = Model.nodoRaiz;
        while (nodoActual != null)
        {
<ul class="collection with-header col s3">
    <li class="collection-item">Club: @nodoActual.id</li>
    <li class="collection-item">Posicion: @nodoActual.nombre</li>
    @*<li class="collection-item center-align"><a href="/Jugador/eliminarJugadorArtesanal/@nodoActual.first_name"><i class="small material-icons red-text">delete</i></a> <a href="/Jugador/listaArtesanal"><i class="small material-icons blue-text">edit</i></a></li>*@
</ul>nodoActual = nodoActual.nodoSiguiente;
            }
        }
    }
</div>